PROTOCOL: "Discharge at 1 C until 2.0 V"
PERIOD: 10
TEMP: -20
PARAMETERS_1: 
  NAME: Negative electrode conductivity [S.m-1]
  BOUNDS: [1.00e-00, 1.00e+01]
  SAMPLE_POINTS: 6
PARAMETERS_2: 
  NAME: Electrolyte diffusivity [m2.s-1]
  BOUNDS: [1.00e-13, 1.00e-13]
  SAMPLE_POINTS: 1
