PROTOCOL: "Discharge at 1 C until 2.0 V"
PERIOD: 10
TEMP: -20
PARAMETERS_INFO:
  PARAMETERS_1: 
    NAME: Positive electrode conductivity [S.m-1]
    BOUNDS: [1.00e-03, 1.00e-02]
    SAMPLE_POINTS: 6
  PARAMETERS_2: 
    NAME: Positive particle diffusivity [m2.s-1]
    BOUNDS: [1.00e-17, 1.00e-16]
    SAMPLE_POINTS: 6
  PARAMETERS_3: 
    NAME: Negative electrode conductivity [S.m-1]
    BOUNDS: [1, 100]
    SAMPLE_POINTS: 6
  PARAMETERS_4: 
    NAME: Negative particle diffusivity [m2.s-1]
    BOUNDS: [1.00e-16, 1.00e-17]
    SAMPLE_POINTS: 6
