Negative particle diffusivity [m2.s-1]: 1.00e-17
Positive particle diffusivity [m2.s-1]: 1.20e-16
Negative electrode conductivity [S.m-1]: 1.00
Positive electrode conductivity [S.m-1]: 0.006024096385542169
Electrolyte diffusivity [m2.s-1]: 3.7455144032921805e-09
Initial concentration in positive electrode [mol.m-3]: 136.914
Initial concentration in negative electrode [mol.m-3]: 24000.0
Cation transference number: 0.25
Positive particle radius [m]: 4.00e-06
Negative particle radius [m]: 1.00e-6
Positive electrode porosity: 0.37
Positive electrode OCP entropic change [V.K-1]: 0.00
Positive electrode charge transfer coefficient: 0.5